import { PrismaClient, InstitutionType, CampusSetting, TestPolicy, AcademicCalendar } from '@prisma/client'
import { SeedFunction } from './seedRunner'

export const universitiesSeed: SeedFunction = {
  name: 'universities',
  seed: async (prisma: PrismaClient) => {
    const universities = [
      {
        name: "Massachusetts Institute of Technology",
        slug: "mit",
        shortName: "MIT",
        description: "A world-class research university in Cambridge, Massachusetts, known for engineering and physical sciences. MIT is renowned for its rigorous academics, cutting-edge research, and innovative culture.",
        city: "Cambridge",
        state: "MA",
        zipCode: "02139",
        country: "USA",
        address: "77 Massachusetts Ave",
        latitude: 42.3601,
        longitude: -71.0942,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/MIT_logo.svg/1024px-MIT_logo.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.mit.edu",
        established: 1861,
        
        climateZone: "Temperate",
        nearestAirport: "Boston Logan (BOS)",
        region: "Northeast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 168,
        
        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",
        
        acceptanceRate: 0.04,
        applicationFee: 75,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-01"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.8,
        avgGpa: 4.17,
        satMath25: 780,
        satMath75: 800,
        satVerbal25: 730,
        satVerbal75: 780,
        actComposite25: 35,
        actComposite75: 36,
        avgSatScore: 1545,
        avgActScore: 35,
        internationalEngReqs: { 
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 57986,
        tuitionOutState: 57986,
        tuitionInternational: 57986,
        roomAndBoard: 18790,
        booksAndSupplies: 1000,
        costOfLiving: 2000,
        percentReceivingAid: 0.58,
        averageGrantAid: 53000,
        averageNetPrice: 15000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 11934,
        undergraduatePopulation: 4638,
        graduatePopulation: 7296,
        studentFacultyRatio: 3,
        percentMale: 0.51,
        percentFemale: 0.49,
        percentInternational: 0.33,
        diversityScore: 0.85,

        graduationRate: 0.95,
        retentionRate: 0.98,
        employmentRate: 0.94,
        averageStartingSalary: 95000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division III",
        hasHousing: true,
        studentLifeScore: 4.5,
        partySceneRating: 3.0,
        safetyRating: 4.8,
        
        popularMajors: ["Computer Science", "Mechanical Engineering", "Mathematics", "Physics", "Electrical Engineering"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Research-focused", "Innovative", "Collaborative", "Tech-oriented"],
        rankings: { usNews: 1, forbes: 2, qs: 1 },
      },
      {
        name: "Stanford University",
        slug: "stanford",
        shortName: "Stanford",
        description: "Located in the heart of Silicon Valley, Stanford is known for its entrepreneurial spirit, academic excellence, and beautiful campus. It's a hub for innovation and startup culture.",
        city: "Stanford",
        state: "CA",
        zipCode: "94305",
        country: "USA",
        address: "450 Serra Mall",
        latitude: 37.4275,
        longitude: -122.1697,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Seal_of_Leland_Stanford_Junior_University.svg/1024px-Seal_of_Leland_Stanford_Junior_University.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.stanford.edu",
        established: 1885,

        climateZone: "Mediterranean",
        nearestAirport: "San Jose (SJC) / SFO",
        region: "West Coast",
        setting: CampusSetting.SUBURBAN,
        campusSizeAcres: 8180,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.039,
        applicationFee: 90,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-05"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.85,
        avgGpa: 4.18,
        satMath25: 770,
        satMath75: 800,
        satVerbal25: 720,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1530,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 62484,
        tuitionOutState: 62484,
        tuitionInternational: 62484,
        roomAndBoard: 19922,
        booksAndSupplies: 1200,
        costOfLiving: 2500,
        percentReceivingAid: 0.56,
        averageGrantAid: 57000,
        averageNetPrice: 16000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 17381,
        undergraduatePopulation: 8049,
        graduatePopulation: 9332,
        studentFacultyRatio: 5,
        percentMale: 0.51,
        percentFemale: 0.49,
        percentInternational: 0.24,
        diversityScore: 0.88,

        graduationRate: 0.94,
        retentionRate: 0.98,
        employmentRate: 0.93,
        averageStartingSalary: 98000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.QUARTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.7,
        partySceneRating: 3.5,
        safetyRating: 4.9,

        popularMajors: ["Computer Science", "Engineering", "Business", "Biology", "Economics"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "MD", "JD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Entrepreneurial", "Innovative", "Collaborative", "Athletic"],
        rankings: { usNews: 3, forbes: 1, qs: 3 },
      },
      {
        name: "University of Oxford",
        slug: "oxford",
        shortName: "Oxford",
        description: "The oldest university in the English-speaking world, Oxford is renowned for its tutorial teaching method and centuries of academic tradition.",
        city: "Oxford",
        state: "Oxfordshire",
        zipCode: "OX1 2JD",
        country: "UK",
        address: "Wellington Square",
        latitude: 51.7548,
        longitude: -1.2544,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-University-Circlet.svg/1200px-Oxford-University-Circlet.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1547516509-03497e61c72b?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.ox.ac.uk",
        established: 1096,

        climateZone: "Temperate",
        nearestAirport: "London Heathrow (LHR)",
        region: "South England",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 500,

        type: InstitutionType.PUBLIC,
        classification: "Collegiate University",

        acceptanceRate: 0.17,
        applicationFee: 75,
        commonAppAccepted: false,
        applicationDeadline: new Date("2023-10-15"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.7,
        avgGpa: 4.0,
        satMath25: 700,
        satMath75: 780,
        satVerbal25: 700,
        satVerbal75: 780,
        actComposite25: 32,
        actComposite75: 35,
        avgSatScore: 1470,
        avgActScore: 33,
        internationalEngReqs: {
          ielts: { minimum: 7.5, recommended: 8.0 },
          toefl: { minimum: 110, recommended: 115 }
        },

        tuitionInState: 12000,
        tuitionOutState: 45000,
        tuitionInternational: 45000,
        roomAndBoard: 15000,
        booksAndSupplies: 800,
        costOfLiving: 12000,
        percentReceivingAid: 0.40,
        averageGrantAid: 20000,
        averageNetPrice: 35000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 24000,
        undergraduatePopulation: 12000,
        graduatePopulation: 12000,
        studentFacultyRatio: 11,
        percentMale: 0.48,
        percentFemale: 0.52,
        percentInternational: 0.45,
        diversityScore: 0.82,

        graduationRate: 0.98,
        retentionRate: 0.97,
        employmentRate: 0.91,
        averageStartingSalary: 75000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 24,

        academicCalendar: AcademicCalendar.TRIMESTER,
        sportsDivision: "None",
        hasHousing: true,
        studentLifeScore: 4.2,
        partySceneRating: 3.5,
        safetyRating: 4.9,

        popularMajors: ["Philosophy", "PPE", "Law", "Medicine", "History"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Traditional", "Academic", "Collegiate", "Historic"],
        rankings: { usNews: 5, forbes: 4, qs: 4 },
      },
      {
        name: "Harvard University",
        slug: "harvard",
        shortName: "Harvard",
        description: "One of the world's most prestigious universities, Harvard is known for academic excellence, influential alumni, and rich history dating back to 1636.",
        city: "Cambridge",
        state: "MA",
        zipCode: "02138",
        country: "USA",
        address: "Massachusetts Hall",
        latitude: 42.3770,
        longitude: -71.1167,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Harvard_shield_wreath.svg/1200px-Harvard_shield_wreath.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.harvard.edu",
        established: 1636,

        climateZone: "Temperate",
        nearestAirport: "Boston Logan (BOS)",
        region: "Northeast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 209,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.031,
        applicationFee: 85,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-01"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.9,
        avgGpa: 4.18,
        satMath25: 750,
        satMath75: 800,
        satVerbal25: 730,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1535,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 54269,
        tuitionOutState: 54269,
        tuitionInternational: 54269,
        roomAndBoard: 19503,
        booksAndSupplies: 1000,
        costOfLiving: 2500,
        percentReceivingAid: 0.55,
        averageGrantAid: 58000,
        averageNetPrice: 13000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 23100,
        undergraduatePopulation: 7100,
        graduatePopulation: 16200,
        studentFacultyRatio: 6,
        percentMale: 0.49,
        percentFemale: 0.51,
        percentInternational: 0.25,
        diversityScore: 0.87,

        graduationRate: 0.97,
        retentionRate: 0.98,
        employmentRate: 0.95,
        averageStartingSalary: 92000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.6,
        partySceneRating: 3.5,
        safetyRating: 4.7,

        popularMajors: ["Economics", "Political Science", "Computer Science", "Psychology", "Social Studies"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Prestigious", "Academic", "Networking", "Historic"],
        rankings: { usNews: 2, forbes: 3, qs: 2 },
      },
      {
        name: "University of California, Berkeley",
        slug: "uc-berkeley",
        shortName: "UC Berkeley",
        description: "A top public research university known for academic excellence, social activism, and innovation. Located in the San Francisco Bay Area.",
        city: "Berkeley",
        state: "CA",
        zipCode: "94720",
        country: "USA",
        address: "200 California Hall",
        latitude: 37.8719,
        longitude: -122.2585,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Seal_of_University_of_California%2C_Berkeley.svg/1200px-Seal_of_University_of_California%2C_Berkeley.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.berkeley.edu",
        established: 1868,

        climateZone: "Mediterranean",
        nearestAirport: "San Francisco (SFO) / Oakland (OAK)",
        region: "West Coast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 1232,

        type: InstitutionType.PUBLIC,
        classification: "Research University",

        acceptanceRate: 0.14,
        applicationFee: 70,
        commonAppAccepted: false,
        applicationDeadline: new Date("2023-11-30"),
        testPolicy: TestPolicy.BLIND,
        minGpa: 3.7,
        avgGpa: 3.89,
        satMath25: 650,
        satMath75: 780,
        satVerbal25: 630,
        satVerbal75: 750,
        actComposite25: 28,
        actComposite75: 34,
        avgSatScore: 1415,
        avgActScore: 31,
        internationalEngReqs: {
          toefl: { minimum: 80, recommended: 100 },
          ielts: { minimum: 6.5, recommended: 7.0 }
        },

        tuitionInState: 14253,
        tuitionOutState: 44206,
        tuitionInternational: 44206,
        roomAndBoard: 17000,
        booksAndSupplies: 1200,
        costOfLiving: 3500,
        percentReceivingAid: 0.65,
        averageGrantAid: 22000,
        averageNetPrice: 18000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 45000,
        undergraduatePopulation: 31000,
        graduatePopulation: 14000,
        studentFacultyRatio: 19,
        percentMale: 0.48,
        percentFemale: 0.52,
        percentInternational: 0.17,
        diversityScore: 0.90,

        graduationRate: 0.91,
        retentionRate: 0.97,
        employmentRate: 0.89,
        averageStartingSalary: 75000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.4,
        partySceneRating: 4.2,
        safetyRating: 4.1,

        popularMajors: ["Computer Science", "Economics", "Political Science", "Engineering", "Business"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Activist", "Diverse", "Innovative", "Public"],
        rankings: { usNews: 20, forbes: 15, qs: 27 },
      },
    ]

    const createdUniversities = await Promise.all(
      universities.map(uni => prisma.university.create({ data: uni }))
    )

    return createdUniversities
  }
}
